export const BASE_URL = "https://sdk-gateway-b85kv8d1.ue.gateway.dev"
export const API_HEADER_KEY = "X-API-Key";
export const SDK_PLATFORM_HEADER_KEY = "X-SDK-Platform";

export const SDK_REFERRAL_CODE_KEY = 'SHINARA_SDK_REFERRAL_CODE';
export const SDK_REFERRAL_PROGRAM_ID_KEY = 'SHINARA_SDK_PROGRAM_ID';
export const SDK_REFERRAL_CODE_ID_KEY = 'SHINARA_SDK_REFERRAL_CODE_ID';
export const SDK_USER_EXTERNAL_USER_ID_KEY = 'SHINARA_SDK_EXTERNAL_USER_ID';
export const SDK_AUTO_GEN_USER_EXTERNAL_ID_KEY = 'SHINARA_SDK_AUTO_GEN_EXTERNAL_USER_ID';
export const SDK_PROCESSED_TRANSACTIONS_KEY = 'SHINARA_SDK_PROCESSED_TRANSACTIONS';
export const SDK_REGISTERED_USERS_KEY = 'SHINARA_SDK_REGISTERED_USERS';

export const REFERRAL_PARAM_KEY = "shinara_ref_code"
